name: test

on:
    workflow_dispatch:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v4

            - name: CraftOS-PC >_
              uses: ./
              with:
                  root: ./test
                  timeout: 5
                  #disable_root: true
                  #directory: ./cc
                  luajit: true
                  #options: --exec print('Hello, World!')
                  #disable_tweaks: true
                  #disable_default_settings: true
                  id: 42
                  #timeout_signal: "KILL"
                  #disable_timeout_verbose: true
                  #timeout_arguments: "--preserve-status"
                  #disable_single: true
                  #disable_headless: true
